{
  "general": {
    "unknownError": "发生未知错误"
  }
}